version: '3.8'
services:
  bot_image:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot_image
    restart: always
    volumes:
      - ./bot/app.log:/app/app.log

  db_image:
    build: ./db
    container_name: db_image
    user: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db_main
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c max_wal_senders=10 
      -c wal_log_hints=on 
      -c max_replication_slots=10
      -c archive_mode=on 
      -c archive_command='cp %p /oracle/pg_data/archive/%f'
      -c log_replication_commands=on

  db_repl_image:
    build: ./db_repl
    container_name: db_repl_image
    user: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      PGUSER: repl_user
      PGPASSWORD: qwerty123
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=db_image --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - db_image