- name: Installing PostgreSQL
  hosts: databases
  become: yes

  tasks:
    - name: Installing PostgreSQL
      apt:
        name:
          - postgresql-14
          - postgresql-contrib-14
    
    - name: Uploading .pgpass
      become_user: postgres
      copy:
        src: .pgpass
        dest: /var/lib/postgresql/.pgpass
        mode: 0600

- name: Setting up PostgreSQL master
  hosts: db
  become: yes

  tasks:
    - name: Starting PostgreSQL
      service:
        name: postgresql
        state: started

    - name: Creating replication user
      become_user: postgres
      shell: psql -c "CREATE USER {{ hostvars['db']['DB_REPL_USER'] }} WITH REPLICATION ENCRYPTED PASSWORD '{{ hostvars['db']['DB_REPL_PASSWORD'] }}';"

    - name: Creating database 
      become_user: postgres
      shell: psql -c "CREATE DATABASE {{ hostvars['db']['DB_DATABASE'] }};"

    - name: Creating tables
      become_user: postgres
      shell: |
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "CREATE TABLE IF NOT EXISTS emails(ID SERIAL PRIMARY KEY, email VARCHAR(255) NOT NULL);"
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "CREATE TABLE IF NOT EXISTS phone_numbers(ID SERIAL PRIMARY KEY, phone_number VARCHAR(20) NOT NULL);"
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "INSERT INTO emails (email) VALUES ('test@test.com'), ('test2@test2.ru');"
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "INSERT INTO phone_numbers (phone_number) VALUES ('88005553535'), ('+7 987 654 32 10');"
    
    - name: Creating users
      become_user: postgres
      shell: |
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "CREATE USER {{ hostvars['db']['DB_USER'] }} WITH ENCRYPTED PASSWORD '{{ hostvars['db']['DB_PASSWORD'] }}';"
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "GRANT SELECT, INSERT ON emails, phone_numbers TO {{ hostvars['db']['DB_USER'] }};"
        psql -d {{ hostvars['db']['DB_DATABASE'] }} -c "GRANT ALL ON SEQUENCE phone_numbers_id_seq, emails_id_seq TO {{ hostvars['db']['DB_USER'] }};"

    - name: Copying postgresql.conf
      template:
        src: postgresql.conf
        dest: /etc/postgresql/14/main/postgresql.conf
    
    - name: Copying pg_hba.conf
      template:
        src: pg_hba.conf
        dest: /etc/postgresql/14/main/pg_hba.conf
    
    - name: Restarting PostgreSQL
      service:
        name: postgresql
        state: restarted

- name:  Setting up PostgreSQL slave
  hosts: db_repl
  become: yes

  tasks:
    - name: Stopping PostgreSQL
      service:
        name: postgresql
        state: stopped
    
    - name: Adding address to postgresql.conf
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        line: "listen_addresses='localhost, {{ hostvars['db']['ansible_host'] }}'"
        insertafter: EOF

    - name: Removing files from /var/lib/postresql/14/main/ folder
      become_user: postgres
      shell: rm -rf /var/lib/postgresql/14/main/*
    
    - name: Running pg_basebackup
      become_user: postgres
      shell: pg_basebackup -R -h {{ hostvars['db']['ansible_host'] }} -U repl_user -D /var/lib/postgresql/14/main
    
    - name: Starting PostgreSQL service
      service:
        name: postgresql
        state: started

- name: Installing requirements and starting bot
  hosts: tg_bot
  become: yes

  tasks:
    - name: Installing Python
      apt:
        name:
          - python3.10-dev
          - libpq-dev
          - git
          - python3-pip

    - name: Cloning repository
      git:
        repo: https://github.com/JettPlay1/PT_START_DevOps.git
        dest: /home/tg_bot

    - name: Installing requirements.txt
      pip:
        requirements: /home/tg_bot/bot/requirements.txt
    
    - name: Copying .env
      copy:
        src: .env
        dest: /home/tg_bot/bot/.env

    - name: Running bot
      shell: "python3 /home/tg_bot/bot/bot.py &"